FROM ubuntu:20.04

ADD containerFiles ExpressDemo/

ENTRYPOINT tail -f /dev/null

WORKDIR ./ExpressDemo

RUN bash init.sh \


#npm install;


#apt-get update; \
#apt-get -y install npm; \ 
#apt-get -y install nodejs; \
#apt-get -y install npm; 


#EXPOSE 8123

#CMD ["node", "server.js"]